# Generated by Django 2.2.5 on 2019-09-10 08:29

import audiobook.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('written_by', models.CharField(max_length=250)),
                ('narrated_by', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('slug', models.SlugField(max_length=48)),
                ('active', models.BooleanField(default=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('album_logo', models.FileField(upload_to='')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='AudiobookTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(max_length=48)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudioPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_name', models.CharField(max_length=250)),
                ('audio_file', models.FileField(default='', upload_to='', validators=[audiobook.models.ext_validators])),
                ('audio_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_part', to='audiobook.Audiobook')),
            ],
        ),
        migrations.CreateModel(
            name='AudiobookImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product-images')),
                ('thumbnail', models.ImageField(null=True, upload_to='product-thumbnails')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiobook.Audiobook')),
            ],
        ),
        migrations.AddField(
            model_name='audiobook',
            name='tags',
            field=models.ManyToManyField(blank=True, to='audiobook.AudiobookTag'),
        ),
    ]
